[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "22"
  NEXT_OUTPUT_EXPORT = "true"

[[redirects]]
  from = "/mockup/*"
  to = "/mockup?slug=:splat"
  status = 200
